#### Machine Learning Models: Logistic Regression

Predict gender-related trends in the population by using machine learning models, such as decision trees or logistic regression. The model can be used to find causes causing gender differences or trained to predict gender based on other demographic features.

In [85]:
# Importing the required libraries:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

In [86]:
# Importing the Dataset 
datapop_df = pd.read_csv("irelandpopulation.csv")

In [87]:
datapop_df.head()

,Statistic Label,CensusYear,Detailed Marital Status,County and City,Sex,Age Group,UNIT,VALUE
0,Population,2011,All marital status,State,Both sexes,All ages,Number,4588252
1,Population,2011,All marital status,State,Both sexes,Under 25 years,Number,1559840
2,Population,2011,All marital status,State,Both sexes,25 - 29 years,Number,361122
3,Population,2011,All marital status,State,Both sexes,30 - 34 years,Number,393945
4,Population,2011,All marital status,State,Both sexes,35 - 39 years,Number,364261

#### Renaming some columns with the 'rename' methods because it's more appropriate.

In [88]:
datapop_df.rename(columns={'Detailed Marital Status': 'MaritalStatus', 'County and City': 'Area', 
                           'Sex': 'Gender','Age Group': 'AgeGroup', 'VALUE': 'Value' }, inplace = True)
datapop_df.head(2)

,Statistic Label,CensusYear,MaritalStatus,Area,Gender,AgeGroup,UNIT,Value
0,Population,2011,All marital status,State,Both sexes,All ages,Number,4588252
1,Population,2011,All marital status,State,Both sexes,Under 25 years,Number,1559840

In [89]:
datapop_df.shape

(33480, 8)

##### Some variable names contain data entry symbols and characters, and others may necessitate data type translation. I'm going to correct this error in the data.

In this case, the marital status 'Re-married,' 'Married (first marriage),' and 'Registered same-sex civil partnership' appear to be unclear. This must be corrected.

In [90]:
print(datapop_df.MaritalStatus.unique())

['All marital status' 'Single' 'Registered same-sex civil partnership'
 'Married (first marriage)' 'Re-married' 'Separated' 'Divorced' 'Widowed']

In [91]:
datapop_df['MaritalStatus'].replace({'Re-married': 'Remarried', 'Registered same-sex civil partnership': 'Registered Same Sex',
                                     'Married (first marriage)':'Married'}, inplace=True)
print(datapop_df.MaritalStatus.nunique())

8

In [92]:
print(datapop_df.Area.unique())

['State' 'Carlow' 'Dublin City' 'Dún Laoghaire-Rathdown' 'Fingal'
 'South Dublin' 'Kildare' 'Kilkenny' 'Laois' 'Longford' 'Louth' 'Meath'
 'Offaly' 'Westmeath' 'Wexford' 'Wicklow' 'Clare'
 'Cork City and Cork County' 'Kerry' 'Limerick City and County'
 'Tipperary' 'Waterford City and County' 'Galway City' 'Galway County'
 'Leitrim' 'Mayo' 'Roscommon' 'Sligo' 'Cavan' 'Donegal' 'Monaghan']

In [93]:
datapop_df['Area'].replace({'Dún Laoghaire-Rathdown': 'Dun Laoghaire', 'Cork City and Cork County': 'Cork',
                                     'Limerick City and County':'Limerick','Waterford City and County':'Waterford'}, inplace=True)
print(datapop_df.Area.nunique())

31

#### Dropping the columns 'Statistic Label' and 'UNIT'.

For example; The 'Statistic Label' column represents the label/name of the statistic being recorded or measured.
The 'UNIT' column represent the unit of measurement for the 'Value' column. In this case it is a'Number', indicating that the value reflects a count or a numerical quantity.

In [94]:
datapop_df.drop(columns=['Statistic Label','UNIT'],inplace=True, axis=1)
datapop_df.head(2)

   CensusYear       MaritalStatus   Area      Gender        AgeGroup    Value
0        2011  All marital status  State  Both sexes        All ages  4588252
1        2011  All marital status  State  Both sexes  Under 25 years  1559840

I used `inplace=True`, `axis=1`, and the drop method to explicitly tell pandas to delete the desired columns from the DataFrame without establishing a new DataFrame.

#### Dropping some of observations (rows) 

I considered removing a few rows (observations) from the dataset. Naturally, evaluating the data's quality, applicability to the goals of the study, and effect of outliers on the analysis as a whole must come first. Before dropping any observations, I carefully considered the influence on the total dataset and ensured that the remaining data is representative and appropriate for  for addressing the research questions.

In this case, I noticed that some rows are not relevant in this analysis , such as: 'All marital status', 'Both sexes', 'All ages' and 'State', as they only add up to the overall sum of data that we already have in other observations and high outliers are the outcome of this. Dropping them can help streamline the analysis and concentrate on the most important data points.

In [95]:
datapop_df.drop(datapop_df[datapop_df['MaritalStatus'] == 'All marital status'].index, inplace=True)
datapop_df.drop(datapop_df[datapop_df['Gender'] == 'Both sexes'].index, inplace=True)
datapop_df.drop(datapop_df[datapop_df['AgeGroup'] == 'All ages'].index, inplace=True)
datapop_df.drop(datapop_df[datapop_df['Area'] == 'State'].index, inplace=True)
datapop_df.head(2)

      CensusYear MaritalStatus    Area Gender        AgeGroup  Value
1456        2011        Single  Carlow   Male  Under 25 years   9795
1457        2011        Single  Carlow   Male   25 - 29 years   1662

In [96]:
datapop_df.shape

(17640, 6)

* Let's  to convert the variable gender into a binary field, that is, replace “Male” by the value 1, Female by the value 2 and Both sexes by the value 3. The 'Gender' column in the DataFrame datapop_df can be changed in-place without generating a new DataFrame by using the `inplace=True` option in the replace function.

In [97]:
dict_Gender = {'Male':1, 'Female': 2,}
datapop_df['Gender'] = datapop_df['Gender'].map(dict_Gender)

datapop_df['Gender'].replace(dict_Gender, inplace=True)
datapop_df.head(2)

      CensusYear MaritalStatus    Area  Gender        AgeGroup  Value
1456        2011        Single  Carlow       1  Under 25 years   9795
1457        2011        Single  Carlow       1   25 - 29 years   1662

In [98]:
datapop_df.Gender.unique()

array([1, 2], dtype=int64)

Let's to separate numerical and categorical variables to analysis.

In [99]:
cat_cols=datapop_df.select_dtypes(include=['object']).columns
num_cols = datapop_df.select_dtypes(include=np.number).columns.tolist()
print("Categorical Variables:")
print(cat_cols)
print("Numerical Variables:")
print(num_cols)

Categorical Variables:
Index(['MaritalStatus', 'Area', 'AgeGroup'], dtype='object')
Numerical Variables:
['CensusYear', 'Gender', 'Value']

As we can see,  some of the attributes are still category variables. I will handle this by encoding the variables.

#### Categorical Variable Encoding:

I am going to utilise Label Encoding for the categorical values 'AgeGroup' that have a natural order. The Label Encoding assigns a number value to each category.

In order to make sure that the labels are properly assigned to each category, I want to confirm the encoding mapping. Let's construct a dictionary that associates each encoded label with its associated original category in the 'AgeGroup' column.

In [100]:
from sklearn.preprocessing import LabelEncoder
le_encoder = LabelEncoder()
datapop_df['AgeGroup'] = le_encoder.fit_transform(datapop_df['AgeGroup'])
unique_sorted_values = sorted(datapop_df['AgeGroup'].unique())
mapping = dict(zip(unique_sorted_values, range(len(unique_sorted_values))))
print('Encoding Mapping:')

Encoding Mapping:

I can confirm the encoding is appropriately assigned for each group by printing the mapping, ensuring that "Under 25 years" is encoded as 0, "25 - 29 years" as 1, and so on.

In [101]:
for key, value in mapping.items():
    print(f'{key} was encoded as {value}')

0 was encoded as 0
1 was encoded as 1
2 was encoded as 2
3 was encoded as 3
4 was encoded as 4
5 was encoded as 5
6 was encoded as 6
7 was encoded as 7
8 was encoded as 8
9 was encoded as 9
10 was encoded as 10
11 was encoded as 11
12 was encoded as 12
13 was encoded as 13

The mapping between the original categorical values and their associated encoded number labels appears to have worked.

In [102]:
datapop_df.head(2)

      CensusYear MaritalStatus    Area  Gender  AgeGroup  Value
1456        2011        Single  Carlow       1        13   9795
1457        2011        Single  Carlow       1         0   1662

The encoded numerical values are now replaced in the 'AgeGroup' column, enabling for additional analysis and machine learning models.

Categorical Variable Encoding:

Since many of our features involve category variables, we are converting them into numbers using the pandas get_dummies function. The two variables, 'MaritalStatus' 'and Gender' have their columns converted into binary using a label encoder.

In [105]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder() # label encoder 
datapop_df ['AgeGroup']=le.fit_transform(datapop_df['AgeGroup']) 
datapop_df['Area']=le.fit_transform(datapop_df['Area'])

KeyError: 'Area'

In [103]:
datapop_df = pd.get_dummies(datapop_df,drop_first=True)
pd.set_option('display.max_columns',100)#to display all columns

datapop_df.head(2)

,CensusYear,Gender,AgeGroup,Value,MaritalStatus_Married,MaritalStatus_Registered Same Sex,MaritalStatus_Remarried,MaritalStatus_Separated,MaritalStatus_Single,MaritalStatus_Widowed,Area_Cavan,Area_Clare,Area_Cork,Area_Donegal,Area_Dublin City,Area_Dun Laoghaire,Area_Fingal,Area_Galway City,Area_Galway County,Area_Kerry,Area_Kildare,Area_Kilkenny,Area_Laois,Area_Leitrim,Area_Limerick,Area_Longford,Area_Louth,Area_Mayo,Area_Meath,Area_Monaghan,Area_Offaly,Area_Roscommon,Area_Sligo,Area_South Dublin,Area_Tipperary,Area_Waterford,Area_Westmeath,Area_Wexford,Area_Wicklow
1456,2011,1,13,9795,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1457,2011,1,0,1662,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

Now our almost data values is 0 and 1 except few features like'MaritalStatus’ and 'CensusYear’, we can use standard scaler we and convert those features in same scale.

In [104]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
train_col_sacle = datapop_df[['MaritalStatus','CensusYear']]
train_scaler_col = scaler.fit_transform(train_col_sacle)
train_scaler_col = pd.DataFrame(train_scaler_col,columns=train_col_sacle.columns)
datapop_df['MaritalStatus']= train_scaler_col['MaritalStatus']
datapop_df['CensusYear']= train_scaler_col['CensusYear']

datapop_df.head(2)

KeyError: "['MaritalStatus'] not in index"

In [ ]:
#Splitting the dataset into the Training set and Test set
X = datapop_df.iloc[:, [2, 3]].values
y = datapop_df.iloc[:, -1].values
datapop_df.head()

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

## Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
#Training the Decision Tree Classification model on the Training set
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(max_depth = 3, random_state = 0)
classifier.fit(X_train, y_train)

In [ ]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [ ]:
# Making the Confusion Matrix
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns

# Calculate cm by calling a method named as 'confusion_matrix'
cm = confusion_matrix(y_test, y_pred)

# Call a method heatmap() to plot confusion matrix
sns.heatmap(cm, annot = True)

# print the classification_report based on y_test and y_predict
print(classification_report(y_test, y_pred))

In [ ]:
 # Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics                          
import warnings
warnings.filterwarnings('ignore') # We can suppress the warnings

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

In [ ]:
import matplotlib.pyplot as plt
plt.figure(figsize=(12,8))

from sklearn import tree
tree.plot_tree(classifier.fit(X_train, y_train))